### ISSUE TITLE
[Bug] 2.3.1 broke `observes` modifier

### ISSUE THREAD

**Issue by esbanarango** [machty/ember-concurrency#481]
### 🐞 Bug description

With the latest version of `ember-concurrency` the _observes_ modifier stopped working.

```js
import Model, { attr } from '@ember-data/model';
import { inject as service } from '@ember/service';
import { task } from 'ember-concurrency';

export default class Parking extends Model {
  @service store;

  @attr('array', { defaultValue: () => [] }) carIds;

  // This tasks should perform everytime `cardIds` changes.
  @task({
    observes: 'carIds.[]',
    drop: true,
  })
  *loadCarsTask() {
    // ...
  }
}
```

```js
import Component from '@glimmer/component';
import { action, set } from '@ember/object';

export default class ParkingBox extends Component {
  @action
  onCarChange(cars) {
    const { parking } = this.args;
    const cardIds = cars.map(({ id }) => parseInt(id));

    set(parking, 'cardIds', cardIds);
  }
}

```
### 😕 Actual Behavior
`loadCarsTask` isn't performing when `carIds` changes.

### 🤔 Expected Behavior
`loadCarsTask` should perform everytime `cardIds` changes.

### 🌍 Environment
- ember-concurrency  `2.3.1`
- ember-source  `4.6.0`
- ember-data `4.2.0`

**Comment by esbanarango** [comment]
@machty We didn't bump those two together. `observes` functionality was working with:

ember-concurrency `2.2.1`
ember-source `4.6.0`
ember-data `4.2.0`

**Comment by esbanarango** [comment]
Yeah, no usage of `ember-concurrency-decorators` at all.

**Comment by robclancy** [comment]
Seems like `on: 'init'` isn't working either (always felt dirty using it anyway, just being lazy). Downgrading to find version where it does work until we update everything to the new syntax.

**Comment by buschtoens** [comment]
I can confirm the `{ on: 'init' }` bug as well. Fortunately we were only using this in a single service, which we fixed by calling `.perform()` in the `init()` hook.

**Comment by machty** [comment]
I think it makes sense to mark this as `wontfix`, not out of laziness, but because Ember is heading in a different direction.

The technical reason these broke is that the new API is assigning a property at object initialization time, whereas the previous approaches manipulate the prototype (a requirement for event-based / observer stuff to work). There are probably ways to fix these APIs, but observers are already deprecated and with `on init` you can just put the perform in the constructor.

Happy to hear feedback on this but otherwise we're probably not gonna fix this.

**Comment by esbanarango** [comment]
@machty, Agreed on moving forward with Ember's direction. But this **breaking change** should probably be added in a major release.

**Comment by machty** [comment]
@esbanarango ohh... I apologize; to clarify, we shouldn't support observes in the new API, but I agree we should fix whatever broke about the old API. I'll take a closer look shortly.

**Comment by machty** [comment]
Fixed in v2.3.4

**Comment by esbanarango** [comment]
@machty this is still failing if we use the new "syntax":

### Fails
```js
// Won't perform when `cardIds` changes
loadCarsTask = task(
  {
    observes: 'carIds.[]',
    drop: true,
  },
  async () => {

  }
)
```

### Works fine
```js
  @task({
    observes: 'carIds.[]',
    drop: true,
  })
  *loadCarsTask() {
    // ...
  }
```

This maybe fine for now, but worth mentioning.

**Comment by machty** [comment]
@esbanarango Yes, I think it is probably not a good idea for us to try and fix this for the new API as it would add further complexity to the EC codebase to accommodate a deprecated pattern.

**Comment by AmilKey** [comment]
@machty it is possible to add information on the new syntax about these events `on: "init", observes: "" `, because I spent a lot of time trying to figure out why it stopped working after upgrading to a new version
