### ISSUE TITLE
The new API doesn't seem to work with ember-cli-code-coverage

### ISSUE THREAD

**Issue by mayatron** [machty/ember-concurrency#483]
The new api doesn't seem to work with the latest `ember-cli-code-coverage@2.0.0-beta.4` when running with `COVERAGE=true`. See this issue I just filed: https://github.com/kategengler/ember-cli-code-coverage/issues/361

I suspect this is an issue with the code coverage addon and not this one, but I thought it might be useful to mention here in case others are stumbling into this.

Btw, the new api is really nice. 🚀  Thanks!

**Comment by machty** [comment]
@mayatron can you try changing your ember-concurrency in package.json to "https://github.com/machty/ember-concurrency.git#maybe-fix-code-coverage"? Trying to see whether #490 fixes the issue.

**Comment by mayatron** [comment]
> @mayatron can you try changing your ember-concurrency in package.json to "https://github.com/machty/ember-concurrency.git#maybe-fix-code-coverage"? Trying to see whether #490 fixes the issue.

Tested, and works for me!

**Comment by machty** [comment]
Fixed in 2.3.5

**Comment by olyckne** [comment]
Hm, still doesn't work here on 2.3.5.
Tried with both `ember-cli-code-coverage@1.0.3` and `2.0.0-beta.4`

Same issue on a new ember app
Made a reproduction repo here: https://github.com/olyckne/ember-concurrency-arrow-fn-code-coverage-issue

**Comment by machty** [comment]
@olyckne thank you for the repro, I believe I narrowed it down in #492. Can you give that PR a try in your app?

**Comment by olyckne** [comment]
@machty yes! That works both in my app and the reproduction repo! :tada:

**Comment by machty** [comment]
Fixed in 2.3.6
